### ISSUE TITLE
Can't compile on Linux

### ISSUE THREAD

**Issue by joaompssantos** [astolap/WaSP#4]
Hi,

I have been trying for sometime but can't seem to be able to compile on Linux with the provided instructions / makefile. This has been tried in Ubuntu 16.04 and 18.04 as well as Gentoo.

Initially some errors appear regarding to functions like 'floor' and 'memset' not being defined (easily fixed by including cmath and cstring). But then some errors appear related to undefined references to some of the code functions:

**source/wasp-decoder.o: In function `main':
wasp-decoder.cpp:(.text.startup+0x58d): undefined reference to `codestreamToViewHeader(int&, view*, _IO_FILE*, minimal_config&)'
collect2: error: ld returned 1 exit status
makefile:14: recipe for target 'wasp-decoder-bin' failed
make: *** [wasp-decoder-bin] Error 1
make: *** Waiting for unfinished jobs....
source/wasp-encoder.o: In function `main':
wasp-encoder.cpp:(.text.startup+0xdbe): undefined reference to `viewHeaderToCodestream(int&, view*, _IO_FILE*, int)'
wasp-encoder.cpp:(.text.startup+0xdec): undefined reference to `viewHeaderToCodestream(int&, view*, _IO_FILE*, int)'
collect2: error: ld returned 1 exit status
makefile:11: recipe for target 'wasp-encoder-bin' failed
make: *** [wasp-encoder-bin] Error 1**

I might be doing something wrong, but at this time I can't figure out what that could be.

Thanks for your help!

**Comment by astolap** [comment]
Hi João,

The problem is in the makefile which is missing codestream.cpp as g++ input . I use the VS solution on Windows instead of the makefile, and this is why I forgot to update the makefile to include the changes. Right now I can't test the makefile, but adding codestream.cpp there should fix the problem.

You can also use the JPEG Pleno LF VM2.0 software to run WaSP.

Best,
Pekka
